# Copyright (c) 2022 Andrea Cervesato <andrea.cervesato@suse.com>

name: "Test LTX package"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - container: "debian:stable"
            env:
              DEBIAN_FRONTEND: noninteractive 
              INSTALL_PYTHON: apt-get update && apt-get -y install gcc clang python3-pip

          - container: "debian:testing"
            env:
              DEBIAN_FRONTEND: noninteractive 
              INSTALL_PYTHON: apt-get update && apt-get -y install gcc clang python3-pip

          - container: "ubuntu:impish"
            env:
              DEBIAN_FRONTEND: noninteractive 
              INSTALL_PYTHON: apt-get update && apt-get -y install gcc clang python3-pip

          - container: "ubuntu:xenial"
            env:
              DEBIAN_FRONTEND: noninteractive 
              INSTALL_PYTHON: apt-get update && apt-get -y install gcc clang python3-pip

          - container: "fedora:latest"
            env:
              INSTALL_PYTHON: yum update -y && yum install -y gcc clang python3-pip

          - container: "opensuse/leap"
            env:
              INSTALL_DEPS: zypper --non-interactive refresh && zypper --non-interactive --ignore-unknown install gcc clang git-lfs

          - container: "alpine:latest"
            env:
              INSTALL_PYTHON: apk update && apk add build-base linux-headers libexecinfo libexecinfo-dev clang py3-pip

    container:
      image: ${{ matrix.container }}
      env: ${{ matrix.env }}
      options: --security-opt seccomp=unconfined

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Install dependences
      run: |
        echo $INSTALL_PYTHON 
        eval $INSTALL_PYTHON

    - name: Git checkout
      uses: actions/checkout@v3

    - name: Build using GCC
      run: gcc ltx/ltx.c -o gcc.out
